// cli_help.v — CLI 帮助文案与命令元数据
module main

const cli_usage_lines = [
	'v-browser — Chrome 自动化 CLI (CDP 协议)',
	'注：server 非必须，connect 时会自动启动 server',
	'',
	'用法:',
	'  v-browser server              启动中继 WebSocket 服务 (可选)',
	'  v-browser server stop         停止中继服务',
	'  v-browser server restart      重启中继服务',
	'  v-browser status              检查服务状态',
	'  v-browser connect [<url>]     连接扩展/标签页 (--extension-id <id>, --tab-id <id>, --window-id <id>, --url <url>)',
	'  v-browser open <url>          导航到 URL',
	'  v-browser close               关闭标签页',
	'  v-browser back                后退',
	'  v-browser forward             前进',
	'  v-browser reload              刷新页面',
	'  v-browser screenshot [path]   截图 (--full --format png|jpeg)',
	'  v-browser pdf <path>          生成 PDF',
	'  v-browser snapshot            Accessibility 快照 (@eN 引用) (--extra --maxNodes N)',
	'  v-browser eval <expr>         执行 JS 表达式',
	'  v-browser eval --file x.js    从文件执行 JS',
	'  v-browser eval --stdin        从标准输入执行 JS',
	'  v-browser eval --base64 <b64> 以 base64 传入 JS',
	'  v-browser click <selector>    点击元素',
	'  v-browser dblclick <selector> 双击元素',
	'  v-browser download <sel> <path> 点击并等待下载完成',
	'  v-browser hover <selector>    鼠标悬停',
	'  v-browser focus <selector>    聚焦元素',
	'  v-browser fill <sel> <text>   清空并填入文本 (--verify --verify-timeout N)',
	'  v-browser type <sel> <text>   追加输入文本 (--verify --verify-timeout N)',
	'  v-browser press <key>         按键 (Enter, Tab, Escape, Control+a ...)',
	'  v-browser keyboard type <text>        模拟真实按键输入（当前焦点）',
	'  v-browser keyboard inserttext <text>  插入文本（无按键事件）',
	'  v-browser select <sel> <val>  选择 <select> 选项',
	'  v-browser check <sel>         勾选复选框',
	'  v-browser uncheck <sel>       取消勾选复选框',
	'  v-browser scroll <dir>        滚动 (up/down/left/right) (--px N --selector sel)',
	'  v-browser scrollintoview <sel> 滚动使元素可见',
	'  v-browser drag --from <sel> --to <sel>  拖拽',
	'  v-browser upload <sel> <files>  文件上传 (逗号分隔) (--verify --wait-preview --preview-selector sel)',
	'  v-browser get <prop> [sel]    获取属性 (text/html/value/title/url/count/attr/box)',
	'  v-browser text <selector>     获取元素文本',
	'  v-browser html <selector>     获取元素 HTML',
	'  v-browser title               获取页面标题',
	'  v-browser url                 获取当前 URL',
	'  v-browser is <state> <sel>    检查状态 (visible/enabled/checked)',
	'  v-browser wait <ms|sel>       等待 (毫秒 / 选择器 / --load / --url / --text / --fn / --download)',
	'  v-browser find --role button --name "OK" --click  语义定位 (--index N --debug --list)',
	'  v-browser tab list            列出标签页',
	'  v-browser tab new [url]       新建标签页',
	'  v-browser tab close [id]      关闭标签页',
	'  v-browser tab switch <id>     切换标签页',
	'  v-browser window new [url]    新建窗口',
	'  v-browser mouse <action> <x> <y>  鼠标原始操作 (move/down/up/click/wheel)',
	'  v-browser cookies get         获取 Cookie (--name <name>)',
	'  v-browser cookies set         设置 Cookie (--name <name> --value <value> --domain <domain>)',
	'  v-browser cookies clear       清除 Cookie (--domain <domain>)',
	'  v-browser storage get         获取 localStorage (--key <key>)',
	'  v-browser storage set         设置 localStorage (--key <key> --value <value>)',
	'  v-browser storage clear       清除 localStorage',
	'  v-browser network requests    列出 CDP 网络请求 (--filter <url> --limit <n> --capture-body --mime <type> --status <200|2xx> --domain <host> --type <XHR|Fetch|...>)',
	'  v-browser network body <requestId>  获取响应体',
	'  v-browser network headers <requestId> 获取响应头',
	'  v-browser network save <requestId> <path>  保存响应体到本地',
	'  v-browser network save-images <dir>  批量保存页面图片请求',
	'  v-browser network watch start <dir>    监听网络请求 (--filter <pattern>)',
	'  v-browser network watch stop           停止监听',
	'  v-browser network watch status         查看监听状态',
	'  v-browser network hook start           启动 XHR Hook (--capture-body --capture-response --filter <pattern> --max-body-len <n> --all-frames)',
	'  v-browser network hook stop            停止 Hook',
	'  v-browser network hook status          查看 Hook 状态',
	'  v-browser network hook records         查看记录 (--filter <pattern> --mime <type> --status <200|2xx> --domain <host> --type <fetch|xhr> --limit <n>)',
	'  v-browser network hook replay <record-id>  重放请求 (--dry-run --method <m> --override-url <u>)',
	'  v-browser network inspect      合并查看请求记录，Hook+CDP 去重 (--filter <url> --limit <n> --mime <type> --status <200|2xx> --domain <host> --type <fetch|xhr|Document|...>)',
	'  v-browser frame <selector>    切换到 iframe (--selector sel)',
	'  v-browser dialog accept       接受对话框 (--text <text>)',
	'  v-browser dialog dismiss      拒绝对话框',
	'  v-browser highlight <selector>    高亮元素',
	'  v-browser console             查看控制台消息',
	'  v-browser errors              查看页面错误',
	'  v-browser trace start         开始性能追踪',
	'  v-browser trace stop [path]   停止追踪并保存',
	'  v-browser profiler start      开始 CPU 性能分析',
	'  v-browser profiler stop [path] 停止分析并保存',
	'  v-browser set viewport        设置视口 (--width N --height N --scale N)',
	'  v-browser set device <name>   设置设备预设 (iPhone 14, Pixel 5, ...)',
	'  v-browser set geo <lat> <lng> 设置地理位置',
	'  v-browser set offline [on|off] 设置离线模式',
	'  v-browser set headers <json>  设置请求头',
	'  v-browser set credentials     设置认证 (--username <u> --password <p>)',
	'  v-browser set media <value>   设置媒体偏好 (dark|light)',
	'  v-browser diff snapshot       快照对比 (--baseline <file> --selector <sel>)',
	'  v-browser diff screenshot     截图像素对比 (--baseline <file> --threshold N --full)',
	'  v-browser diff url <url1> <url2>  URL 对比 (--screenshot --wait-until <state>)',
	'  v-browser clipboard read image        读取剪贴板图片',
	'  v-browser clipboard write image <path> 写入图片到剪贴板',
	'  v-browser state save [path]   保存浏览器状态',
	'  v-browser state load [path]   加载浏览器状态',
	'  v-browser state list          列出已保存状态',
	'',
	'选项:',
	'  --selector / -s     CSS 选择器或 XPath (//...) 或 @eN 引用',
	'  --url               URL 参数',
	'  --text              文本内容',
	'  --full              完整页面截图',
	'  --format            图片格式 (png|jpeg)',
	'  --file              从文件读取 eval 内容',
	'  --stdin             从标准输入读取完整 eval 内容',
	'  --base64 / -b       以 base64 传入 eval 内容',
	'  --verify            操作后验证状态',
	'  --verify-timeout    验证超时时间 (毫秒)',
	'  --json              以 JSON 格式输出结果',
	'  --raw / -r          输出原始结果 (不解包 JSON)',
	'',
	'示例 — 网络请求捕获:',
	'  # 只看 POST XHR 请求（含请求体），最多 10 条',
	'  v-browser network requests --filter POST --type XHR --capture-body --limit 10',
	'',
	'  # CDP 层自动缓存响应体，无需再手动调 network body <id>',
	'  v-browser network requests --capture-body',
	'',
	'  # 只看某域名的 4xx 失败请求',
	'  v-browser network requests --domain api.example.com --status 4xx --type XHR',
	'',
	'  # 启动 hook，覆盖所有 iframe，不截断响应体',
	'  v-browser network hook start --all-frames --capture-response --max-body-len 0',
	'',
	'  # 合并查看 hook + CDP 记录（去重），只看 JSON 响应前 20 条',
	'  v-browser network inspect --mime application/json --limit 20',
	'',
	'  # 过滤特定关键词后合并查看',
	'  v-browser network inspect --filter api --domain example.com',
]

fn print_usage() {
	println(cli_usage_lines.join('\n'))
}
